title: Filip Jasic # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Engineer
  <br><br>
  Mainly interested in Python, Go, Django, DevOps, Kubernetes, Docker, but also academically thought C, C++, Java, Verilog
  <br><br>
  Experienced in Automotive and Semiconductor industries.
  <br><br>
  <a href="https://www.linkedin.com/in/filipjasic/">View My LinkedIn Profile</a> 
  
remote_theme: "dracula/gh-pages"
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
