title: Filip Jasic # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Engineer
  <br><br>
  Mainly interested in Python, Go, Django, DevOps, Kubernetes, Docker, but also academically taught C, C++, Java, Verilog, SystemVerilog, VHDL, Matlab.
  <br><br>
  Experienced with both hardware and software in Automotive and Semiconductor industries. Most of the coding I do is under NDA, but here is some of my open-source code.
  <br><br>
  <a href="https://www.linkedin.com/in/filipjasic/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
