title: Filip Jasic # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Engineer
  <br><br>
  Engineer with experience in automotive and semiconductor industry. Interested in technologies that make the world go around.
  <br><br>
  Mainly interested in Python, Go, Jenkins, Github Actions, Kubernetes, Docker, Terraform, Vagrant but also used C, C++, Java, VHDL, Matlab.
  <br><br>
  <a href="https://www.linkedin.com/in/filipjasic/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
