title: Filip Jasic # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Engineer
  <br><br>
  Mainly interested in Python, Go, Django, DevOps, Kubernetes, Docker, but also academically taught C, C++, Java, Verilog
  <br><br>
  Experienced in Automotive R&D and Semiconductor industries.
  <br><br>
  <a href="https://www.linkedin.com/in/filipjasic/">View My LinkedIn Profile</a> 
  
theme: minima
minima:
  skin: dark
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
